import React, { useState } from 'react';
import { motion } from 'motion/react';
import { Sparkles, CheckCircle2, AlertTriangle, Eye, ShieldCheck } from 'lucide-react';
import { CiberMascot } from '../CiberMascot';
import { useLanguage } from '../../i18n/LanguageContext';
import { ChildAgeGroup } from '../../types';

interface AiDetectorGameProps {
  onComplete: () => void;
  ageGroup?: ChildAgeGroup;
}

export const AiDetectorGame: React.FC<AiDetectorGameProps> = ({ onComplete, ageGroup = '8–10' }) => {
  const { language } = useLanguage();
  const [selectedImage, setSelectedImage] = useState<'a' | 'b' | null>(null);
  const [revealed, setRevealed] = useState(false);

  const getAgeMascotText = () => {
    if (ageGroup === '13–14') {
      if (language === 'en') return 'Ciber says: "Synthetic media and deepfakes create subtle lighting inconsistencies, texture blurring, and deformed background text. Always cross-check origins!"';
      if (language === 'fr') return 'Ciber dit : "Les hypertrucages et médias IA créent des reflets incohérents et des textures floues. Vérifie toujours les sources !"';
      return 'Ciber dice: "Los deepfakes y la IA sintética dejan inconsistencias sutiles de luz, bordes difuminados y textos deformes. ¡Verifica siempre la fuente!"';
    }
    if (ageGroup === '11–12') {
      if (language === 'en') return 'Ciber says: "AI-generated avatars in games often have telltale flaws: asymmetric glasses reflections, melted accessories, and 6 fingers."';
      if (language === 'fr') return 'Ciber dit : "Les avatars IA dans les jeux ont souvent des défauts : reflets asymétriques, accessoires déformés et 6 doigts."';
      return 'Ciber dice: "Los avatares de IA en redes y juegos suelen tener errores: lentes con reflejos disparejos, accesorios derretidos y 6 dedos."';
    }
    if (language === 'en') return 'Ciber says: "Look closely at the hands, helmet reflections, and background! Which picture was generated by an AI robot?"';
    if (language === 'fr') return 'Ciber dit : "Observe bien les mains et les reflets du casque ! Quelle image a été créée par une Intelligence Artificielle ?"';
    return 'Ciber dice: "Observa las manos, las letras de fondo y los reflejos en los cascos. ¿Cuál imagen fue creada por una Inteligencia Artificial?"';
  };

  const loc = {
    es: {
      tag: `Mecánica 11 • Nivel ${ageGroup} años`,
      title: 'Detector de IA: ¿Real o Sintético?',
      badge: 'Laboratorio IA',
      mascot: getAgeMascotText(),
      cardATitle: 'Foto A: Misión Espacial',
      cardASub: 'Detalles nítidos, reflejo simétrico',
      imgAName: 'Imagen A',
      imgADesc: 'Fotografía real de museo espacial',
      imgAReveal: 'Fotografía Genuina',
      cardBTitle: 'Foto B: Astronauta IA',
      cardBSub: '¡Guante con 6 dedos y visor deformado!',
      imgBName: 'Imagen B',
      imgBDesc: 'Generada por algoritmo sintético',
      imgBReveal: '¡Generada con IA!',
      correctTitle: '¡Ojo de lince! Detectaste la imagen de IA',
      wrongTitle: 'Mira de cerca la Imagen B:',
      explanation: 'Los generadores de IA a menudo se equivocan con las manos (dibujando dedos de más), funden sombras imposibles o deforman textos de fondo. ¡Siempre investiga la fuente!',
      continueBtn: '¡Continuar con mi Recompensa!',
      selectPrompt: 'Toca la imagen generada por IA',
    },
    fr: {
      tag: 'Mécanique 11 / IA & Hypertrucages',
      title: 'Détecteur IA : Réel ou Synthétique ?',
      badge: 'Labo IA',
      mascot: 'Ciber dit : "Regarde les mains, les lettres d’arrière-plan et les reflets des visières. Quelle image a été générée par une IA ?"',
      cardATitle: 'Photo A : Mission Spatiale',
      cardASub: 'Détails nets, reflet symétrique',
      imgAName: 'Image A',
      imgADesc: 'Vraie photo de musée spatial',
      imgAReveal: 'Photographie Authentique',
      cardBTitle: 'Photo B : Astronaute IA',
      cardBSub: 'Gant à 6 doigts et visière fondue !',
      imgBName: 'Image B',
      imgBDesc: 'Créée par algorithme génératif',
      imgBReveal: 'Générée par IA !',
      correctTitle: 'Œil de lynx ! Tu as démasqué l’IA',
      wrongTitle: 'Observe bien l’Image B :',
      explanation: 'Les générateurs d’IA ratent souvent les mains (doigts supplémentaires), créent des ombres étranges ou déforment les écritures. Vérifie toujours la source !',
      continueBtn: 'Continuer vers ma Récompense !',
      selectPrompt: 'Touche l’image générée par IA',
    },
    en: {
      tag: 'Mechanic 11 / AI & Deepfakes',
      title: 'AI Detector: Real or Synthetic?',
      badge: 'AI Lab',
      mascot: 'Ciber says: "Check the fingers, background typography, and visor reflections. Which picture was created by Artificial Intelligence?"',
      cardATitle: 'Photo A: Space Mission',
      cardASub: 'Crisp details, symmetric reflection',
      imgAName: 'Image A',
      imgADesc: 'Genuine space museum photograph',
      imgAReveal: 'Genuine Photo',
      cardBTitle: 'Photo B: AI Astronaut',
      cardBSub: 'Glove with 6 fingers & distorted visor!',
      imgBName: 'Image B',
      imgBDesc: 'Generated by synthetic algorithm',
      imgBReveal: 'AI Generated!',
      correctTitle: 'Eagle eyes! You spotted the AI image',
      wrongTitle: 'Take a closer look at Image B:',
      explanation: 'AI generators often struggle with fingers (drawing extra ones), blend impossible lighting, or warp letters. Always verify the source!',
      continueBtn: 'Claim My Reward!',
      selectPrompt: 'Tap the image generated by AI',
    },
  }[language] || {
    tag: 'Mecánica 11 / IA & Deepfakes',
    title: 'Detector de IA: ¿Real o Sintético?',
    badge: 'Laboratorio IA',
    mascot: 'Ciber dice: "Observa las manos, las letras de fondo y los reflejos en los cascos. ¿Cuál imagen fue creada por una Inteligencia Artificial?"',
    cardATitle: 'Foto A: Misión Espacial',
    cardASub: 'Detalles nítidos, reflejo simétrico',
    imgAName: 'Imagen A',
    imgADesc: 'Fotografía real de museo espacial',
    imgAReveal: 'Fotografía Genuina',
    cardBTitle: 'Foto B: Astronauta IA',
    cardBSub: '¡Guante con 6 dedos y visor deformado!',
    imgBName: 'Imagen B',
    imgBDesc: 'Generada por algoritmo sintético',
    imgBReveal: '¡Generada con IA!',
    correctTitle: '¡Ojo de lince! Detectaste la imagen de IA',
    wrongTitle: 'Mira de cerca la Imagen B:',
    explanation: 'Los generadores de IA a menudo se equivocan con las manos (dibujando dedos de más), funden sombras imposibles o deforman textos de fondo. ¡Siempre investiga la fuente!',
    continueBtn: '¡Continuar con mi Recompensa!',
    selectPrompt: 'Toca la imagen generada por IA',
  };

  // Card A is Real, Card B is AI generated
  const handleSelect = (choice: 'a' | 'b') => {
    setSelectedImage(choice);
    setRevealed(true);
  };

  const isCorrect = selectedImage === 'b';

  return (
    <div className="flex-1 flex flex-col p-4 bg-slate-50 text-slate-800 select-none overflow-y-auto space-y-3">
      {/* Top Banner */}
      <div className="bg-white rounded-3xl p-4 shadow-sm border border-slate-100 flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="w-11 h-11 rounded-2xl bg-purple-100 text-purple-700 flex items-center justify-center font-bold">
            <Sparkles className="w-6 h-6" />
          </div>
          <div>
            <div className="text-[10px] uppercase font-extrabold text-purple-600 tracking-wider">
              {loc.tag}
            </div>
            <h2 className="text-sm font-black text-slate-900">{loc.title}</h2>
          </div>
        </div>
        <span className="text-xs font-bold px-3 py-1 rounded-full bg-slate-100 text-slate-600">
          {loc.badge}
        </span>
      </div>

      {/* Mascot advice */}
      <div className="flex items-center gap-3 p-3 bg-purple-50/80 rounded-2xl border border-purple-100">
        <CiberMascot size="sm" expression={revealed ? (isCorrect ? 'celebrating' : 'thinking') : 'surprised'} />
        <div className="text-xs text-purple-950 leading-snug">
          {loc.mascot}
        </div>
      </div>

      {/* Two Comparison Cards */}
      <div className="grid grid-cols-2 gap-3 py-1">
        {/* Card A: REAL */}
        <div
          onClick={() => !revealed && handleSelect('a')}
          className={`rounded-3xl border-2 p-3 bg-white transition cursor-pointer flex flex-col justify-between ${
            selectedImage === 'a' ? 'ring-2 ring-purple-400 border-purple-500' : 'border-slate-200 hover:border-slate-300'
          }`}
        >
          <div>
            <div className="h-32 rounded-2xl bg-gradient-to-br from-slate-800 to-slate-900 flex flex-col items-center justify-center p-2 text-center text-white relative overflow-hidden">
              <span className="text-3xl">👨‍🚀</span>
              <span className="text-[10px] font-bold mt-1 text-slate-200">{loc.cardATitle}</span>
              <span className="text-[9px] text-slate-400">{loc.cardASub}</span>
            </div>
            <h3 className="text-xs font-black text-slate-900 mt-2">{loc.imgAName}</h3>
            <p className="text-[10px] text-slate-500">{loc.imgADesc}</p>
          </div>

          {revealed && (
            <div className="mt-2 text-[10px] font-bold px-2 py-1 rounded-xl bg-emerald-50 text-emerald-700 text-center border border-emerald-200">
              {loc.imgAReveal}
            </div>
          )}
        </div>

        {/* Card B: AI GENERATED */}
        <div
          onClick={() => !revealed && handleSelect('b')}
          className={`rounded-3xl border-2 p-3 bg-white transition cursor-pointer flex flex-col justify-between ${
            selectedImage === 'b' ? 'ring-2 ring-purple-400 border-purple-500' : 'border-slate-200 hover:border-slate-300'
          }`}
        >
          <div>
            <div className="h-32 rounded-2xl bg-gradient-to-br from-purple-900 via-indigo-900 to-slate-900 flex flex-col items-center justify-center p-2 text-center text-white relative overflow-hidden">
              <span className="text-3xl">🤖</span>
              <span className="text-[10px] font-bold mt-1 text-purple-200">{loc.cardBTitle}</span>
              <span className="text-[9px] text-purple-300">{loc.cardBSub}</span>
            </div>
            <h3 className="text-xs font-black text-slate-900 mt-2">{loc.imgBName}</h3>
            <p className="text-[10px] text-slate-500">{loc.imgBDesc}</p>
          </div>

          {revealed && (
            <div className="mt-2 text-[10px] font-bold px-2 py-1 rounded-xl bg-purple-100 text-purple-800 text-center border border-purple-200">
              {loc.imgBReveal}
            </div>
          )}
        </div>
      </div>

      {/* Detective explanation on reveal */}
      {revealed && (
        <motion.div
          initial={{ opacity: 0, y: 6 }}
          animate={{ opacity: 1, y: 0 }}
          className={`p-3.5 rounded-2xl text-xs leading-relaxed border ${
            isCorrect
              ? 'bg-emerald-50 border-emerald-200 text-emerald-950'
              : 'bg-sky-50 border-sky-200 text-sky-950'
          }`}
        >
          <div className="font-bold flex items-center gap-1.5 mb-1">
            {isCorrect ? (
              <>
                <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                <span>{loc.correctTitle}</span>
              </>
            ) : (
              <>
                <Eye className="w-4 h-4 text-sky-600" />
                <span>{loc.wrongTitle}</span>
              </>
            )}
          </div>
          <p>
            {loc.explanation}
          </p>
        </motion.div>
      )}

      {/* Completion CTA */}
      <button
        onClick={onComplete}
        disabled={!revealed}
        className={`w-full py-3.5 rounded-2xl font-black text-sm transition-all flex items-center justify-center gap-2 cursor-pointer ${
          revealed
            ? 'bg-gradient-to-r from-purple-500 to-indigo-600 text-white shadow-lg shadow-purple-500/20 active:scale-95'
            : 'bg-slate-200 text-slate-400 cursor-not-allowed'
        }`}
      >
        <ShieldCheck className="w-4 h-4" />
        <span>{revealed ? loc.continueBtn : loc.selectPrompt}</span>
      </button>
    </div>
  );
};
