import { World, AchievementBadge, UserProfile, GameHotspot } from './types';

export const INITIAL_PROFILE: UserProfile = {
  nickname: 'LucasCyber',
  avatarId: 'bot-blue',
  avatarColor: '#0284C7',
  ageGroup: '11–12',
  level: 3,
  xp: 680,
  xpToNextLevel: 1000,
  coins: 240,
  streakDays: 4,
  skills: {
    privacidad: 82,
    contrasenas: 65,
    phishing: 48,
    redesSociales: 55,
    gamingSeguro: 40,
    amigosDesconocidos: 35,
    dispositivos: 30,
    ciberacoso: 45,
    iaDeepfakes: 25,
    respuestaIncidentes: 20,
  },
  completedMissions: ['w1-m1', 'w1-m2', 'w1-m3'],
  unlockedBadges: ['badge-first-step', 'badge-password-apprentice'],
};

export const AVATAR_OPTIONS = [
  { id: 'bot-blue', name: 'Cyberbot', icon: '🤖', color: '#0284C7', bg: 'bg-sky-100 text-sky-700' },
  { id: 'cat-cyber', name: 'NanoCat', icon: '🐱', color: '#8B5CF6', bg: 'bg-purple-100 text-purple-700' },
  { id: 'fox-cyber', name: 'PixelFox', icon: '🦊', color: '#F97316', bg: 'bg-orange-100 text-orange-700' },
  { id: 'owl-shield', name: 'ShieldOwl', icon: '🦉', color: '#10B981', bg: 'bg-emerald-100 text-emerald-700' },
  { id: 'bear-guardian', name: 'ByteBear', icon: '🐻', color: '#06B6D4', bg: 'bg-cyan-100 text-cyan-700' },
  { id: 'hero-space', name: 'AstroKid', icon: '🚀', color: '#EC4899', bg: 'bg-pink-100 text-pink-700' },
];

export const WORLDS_DATA: World[] = [
  {
    id: 'world-1',
    number: 1,
    name: 'Isla Privacidad',
    title: 'Identidad & Privacidad',
    subtitle: 'Protege lo que te hace único en el mundo digital.',
    motto: 'Tus datos son tu tesoro',
    biome: 'Archipiélago paradisíaco con torres de vigilancia y radares de datos',
    status: 'active',
    icon: 'Shield',
    color: '#0284C7',
    accentBg: 'from-sky-50 to-cyan-100/70',
    completedMissions: 3,
    totalMissions: 8,
    finalChallengeTitle: 'El Investigador de Privacidad',
    finalChallengeDesc: 'Audita un perfil completo de red social y elimina 5 huellas de privacidad antes de que se haga público.',
    missions: [
      {
        id: 'w1-m1',
        worldId: 'world-1',
        number: 1,
        title: '¿Qué compartirías?',
        subtitle: 'Examina una foto escolar antes de subirla.',
        gameType: 'image-detection',
        difficulty: 'Fácil',
        xpReward: 100,
        coinReward: 25,
        skillBonus: { skill: 'privacidad', points: 8 },
        status: 'available',
        description: 'Una foto parece inocente, pero contiene 4 detalles que revelan dónde vives y estudias.',
        timeEstimate: '3 min',
      },
      {
        id: 'w1-m2',
        worldId: 'world-1',
        number: 2,
        title: 'El Cuadrante Privado',
        subtitle: 'Ajusta el dial de visibilidad de tu perfil.',
        gameType: 'privacy-dial',
        difficulty: 'Fácil',
        xpReward: 110,
        coinReward: 25,
        skillBonus: { skill: 'privacidad', points: 9 },
        status: 'available',
        description: 'Experimenta con los controles: Público, Amigos o Solo yo, y observa qué ve un extraño.',
        timeEstimate: '3 min',
      },
      {
        id: 'w1-m3',
        worldId: 'world-1',
        number: 3,
        title: 'Detective de Datos',
        subtitle: 'Clasifica datos entre públicos y secretos.',
        gameType: 'safe-risky-sort',
        difficulty: 'Fácil',
        xpReward: 120,
        coinReward: 30,
        skillBonus: { skill: 'privacidad', points: 10 },
        status: 'available',
        description: 'Arrastra tarjetas a la zona Segura o Riesgosa según el tipo de información personal.',
        timeEstimate: '4 min',
      },
      {
        id: 'w1-m4',
        worldId: 'world-1',
        number: 4,
        title: 'El Radar GPS Oculto',
        subtitle: 'Desactiva metadatos de ubicación en fotos.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 130,
        coinReward: 30,
        skillBonus: { skill: 'privacidad', points: 10 },
        status: 'locked',
        description: 'Aprende cómo las fotos guardan coordenadas exactas y cómo apagarlas.',
        timeEstimate: '3 min',
      },
      {
        id: 'w1-m5',
        worldId: 'world-1',
        number: 5,
        title: 'Parejas de Identidad',
        subtitle: 'Memoria de conceptos clave de privacidad.',
        gameType: 'memory-match',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'privacidad', points: 11 },
        status: 'locked',
        description: 'Encuentra las parejas de símbolos de seguridad para revelar consejos prácticos.',
        timeEstimate: '4 min',
      },
      {
        id: 'w1-m6',
        worldId: 'world-1',
        number: 6,
        title: 'El Nickname Perfecto',
        subtitle: 'Construye un alias gamer 100% seguro.',
        gameType: 'drag-drop',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'privacidad', points: 12 },
        status: 'locked',
        description: 'Combina palabras geniales sin incluir tu año de nacimiento ni tu nombre real.',
        timeEstimate: '3 min',
      },
      {
        id: 'w1-m7',
        worldId: 'world-1',
        number: 7,
        title: 'El Círculo de Confianza',
        subtitle: '¿Quién tiene acceso a tus historias?',
        gameType: 'chat-sim',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'privacidad', points: 12 },
        status: 'locked',
        description: 'Decide cómo reaccionar cuando un compañero te pide compartir tu ubicación en vivo.',
        timeEstimate: '4 min',
      },
      {
        id: 'w1-m8',
        worldId: 'world-1',
        number: 8,
        title: 'El Gran Inspector de Privacidad',
        subtitle: 'Misión Boss: Audita una cuenta antes de publicarla.',
        gameType: 'puzzle-vault',
        difficulty: 'Difícil',
        xpReward: 250,
        coinReward: 70,
        skillBonus: { skill: 'privacidad', points: 20 },
        status: 'locked',
        isBoss: true,
        bossName: 'El Gran Filtro',
        description: 'Desafío final del Mundo 1: Encuentra los 5 errores críticos de privacidad para ganar la Copa de la Isla.',
        timeEstimate: '6 min',
      },
    ],
  },
  {
    id: 'world-2',
    number: 2,
    name: 'Fortaleza de Contraseñas',
    title: 'Contraseñas & Cuentas',
    subtitle: 'Construye defensas difíciles de romper para tus perfiles.',
    motto: 'Una llave débil abre todas tus puertas',
    biome: 'Imponente castillo futurista con bóvedas de acero, engranajes y cerraduras biométricas',
    status: 'unlocked',
    icon: 'KeyRound',
    color: '#8B5CF6',
    accentBg: 'from-purple-50 to-indigo-100/70',
    completedMissions: 1,
    totalMissions: 8,
    finalChallengeTitle: 'La Bóveda Impenetrable',
    finalChallengeDesc: 'Configura una cuenta maestra con contraseña de 16 caracteres y verificación en dos pasos bajo ataque simulado.',
    missions: [
      {
        id: 'w2-m1',
        worldId: 'world-2',
        number: 1,
        title: 'La Forja de Contraseñas',
        subtitle: 'Crea una llave secreta de nivel legendario.',
        gameType: 'password-forge',
        difficulty: 'Fácil',
        xpReward: 120,
        coinReward: 30,
        skillBonus: { skill: 'contrasenas', points: 10 },
        status: 'available',
        description: 'Observa en vivo el medidor de fuerza y el tiempo estimado que tardaría un robot en adivinarla.',
        timeEstimate: '3 min',
      },
      {
        id: 'w2-m2',
        worldId: 'world-2',
        number: 2,
        title: 'El Constructor de Llaves',
        subtitle: 'Arrastra ingredientes seguros a la bóveda.',
        gameType: 'drag-drop',
        difficulty: 'Fácil',
        xpReward: 125,
        coinReward: 30,
        skillBonus: { skill: 'contrasenas', points: 10 },
        status: 'available',
        description: 'Descarta contraseñas típicas como "123456" y junta símbolos, mayúsculas y palabras aleatorias.',
        timeEstimate: '3 min',
      },
      {
        id: 'w2-m3',
        worldId: 'world-2',
        number: 3,
        title: 'El Escudo Doble (2FA)',
        subtitle: '¿Por qué necesitas un segundo código?',
        gameType: 'puzzle-vault',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'contrasenas', points: 12 },
        status: 'locked',
        description: 'Descubre cómo la verificación en dos pasos salva tu cuenta aunque adivinen tu contraseña.',
        timeEstimate: '4 min',
      },
      {
        id: 'w2-m4',
        worldId: 'world-2',
        number: 4,
        title: 'La Trampa de la Misma Clave',
        subtitle: 'El efecto dominó de usar una sola contraseña.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 130,
        coinReward: 30,
        skillBonus: { skill: 'contrasenas', points: 10 },
        status: 'locked',
        description: 'Si filtran la clave de un foro de juegos, ¿está a salvo tu correo electrónico?',
        timeEstimate: '3 min',
      },
      {
        id: 'w2-m5',
        worldId: 'world-2',
        number: 5,
        title: 'Memoria de Bóveda',
        subtitle: 'Empareja conceptos de ciberdefensa.',
        gameType: 'memory-match',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'contrasenas', points: 11 },
        status: 'locked',
        description: 'Encuentra las parejas de cerraduras, códigos temporales y gestores de contraseñas.',
        timeEstimate: '4 min',
      },
      {
        id: 'w2-m6',
        worldId: 'world-2',
        number: 6,
        title: 'El Amigo que Pide la Cuenta',
        subtitle: 'Historia interactiva: "Préstame tu perfil 5 minutos".',
        gameType: 'chat-sim',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'contrasenas', points: 12 },
        status: 'locked',
        description: 'Un amigo te pide tu contraseña para probar una skin. Aprende a decir que no con amabilidad.',
        timeEstimate: '4 min',
      },
      {
        id: 'w2-m7',
        worldId: 'world-2',
        number: 7,
        title: 'Preguntas Secretas con Truco',
        subtitle: 'Por qué no usar el nombre de tu perro real.',
        gameType: 'safe-risky-sort',
        difficulty: 'Media',
        xpReward: 160,
        coinReward: 45,
        skillBonus: { skill: 'contrasenas', points: 13 },
        status: 'locked',
        description: 'Aprende a elegir preguntas de recuperación que nadie pueda investigar en tus fotos.',
        timeEstimate: '4 min',
      },
      {
        id: 'w2-m8',
        worldId: 'world-2',
        number: 8,
        title: 'El Asedio a la Fortaleza',
        subtitle: 'Misión Boss: Resiste 3 ataques de fuerza bruta.',
        gameType: 'password-forge',
        difficulty: 'Difícil',
        xpReward: 260,
        coinReward: 75,
        skillBonus: { skill: 'contrasenas', points: 22 },
        status: 'locked',
        isBoss: true,
        bossName: 'El Cracker Automático',
        description: 'Desafío final del Mundo 2: Diseña 3 contraseñas blindadas contra diccionarios automatizados.',
        timeEstimate: '6 min',
      },
    ],
  },
  {
    id: 'world-3',
    number: 3,
    name: 'Puerto Phishing',
    title: 'Phishing & Estafas',
    subtitle: 'Aprende a detectar trampas, anzuelos y premios falsos.',
    motto: 'Si parece demasiado bueno, desconfía',
    biome: 'Puerto pesquero tech con faros de advertencia, anzuelos luminosos y boyas de seguridad',
    status: 'unlocked',
    icon: 'FishSymbol',
    color: '#F59E0B',
    accentBg: 'from-amber-50 to-orange-100/70',
    completedMissions: 0,
    totalMissions: 8,
    finalChallengeTitle: 'La Tormenta de Phishing',
    finalChallengeDesc: 'Filtra 8 mensajes de correo y SMS a contrarreloj sin caer en ningún enlace malicioso.',
    missions: [
      {
        id: 'w3-m1',
        worldId: 'world-3',
        number: 1,
        title: 'Bandeja de Entrada Simulada',
        subtitle: 'Examina 5 mensajes y detecta trampas.',
        gameType: 'phishing-inbox',
        difficulty: 'Fácil',
        xpReward: 130,
        coinReward: 30,
        skillBonus: { skill: 'phishing', points: 12 },
        status: 'available',
        description: 'Toca el remitente, enlaces falsos, faltas de ortografía y tono de urgencia.',
        timeEstimate: '4 min',
      },
      {
        id: 'w3-m2',
        worldId: 'world-3',
        number: 2,
        title: 'El Anzuelo de Monedas Gratis',
        subtitle: '¿Robux o Pavos gratis a cambio de tus datos?',
        gameType: 'chat-sim',
        difficulty: 'Fácil',
        xpReward: 125,
        coinReward: 30,
        skillBonus: { skill: 'phishing', points: 11 },
        status: 'available',
        description: 'Un bot te promete gemas ilimitadas si abres un enlace misterioso. ¿Qué respondes?',
        timeEstimate: '3 min',
      },
      {
        id: 'w3-m3',
        worldId: 'world-3',
        number: 3,
        title: 'Detectando Enlaces Gemelos',
        subtitle: 'Distingue urls legítimas de imitaciones.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 135,
        coinReward: 35,
        skillBonus: { skill: 'phishing', points: 12 },
        status: 'locked',
        description: 'Aprende a notar letras cambiadas como "arnazon.com" o "paypa1.com" antes de hacer clic.',
        timeEstimate: '4 min',
      },
      {
        id: 'w3-m4',
        worldId: 'world-3',
        number: 4,
        title: 'Clasificador de Mensajes',
        subtitle: 'Separa correos legítimos de trampas.',
        gameType: 'safe-risky-sort',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'phishing', points: 13 },
        status: 'locked',
        description: 'Arrastra notificaciones al bote de basura o a la bandeja segura con agilidad.',
        timeEstimate: '4 min',
      },
      {
        id: 'w3-m5',
        worldId: 'world-3',
        number: 5,
        title: 'La Falsa Urgencia',
        subtitle: '¡Tu cuenta será cerrada en 10 minutos!',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 40,
        skillBonus: { skill: 'phishing', points: 13 },
        status: 'locked',
        description: 'Por qué los atacantes usan el miedo y la prisa para que no pienses antes de actuar.',
        timeEstimate: '3 min',
      },
      {
        id: 'w3-m6',
        worldId: 'world-3',
        number: 6,
        title: 'El Premio Misterioso',
        subtitle: 'Has ganado la consola del año... ¿o no?',
        gameType: 'incident-response',
        difficulty: 'Media',
        xpReward: 155,
        coinReward: 45,
        skillBonus: { skill: 'phishing', points: 14 },
        status: 'locked',
        description: 'Toma decisiones paso a paso al recibir una notificación de premio sorpresa.',
        timeEstimate: '4 min',
      },
      {
        id: 'w3-m7',
        worldId: 'world-3',
        number: 7,
        title: 'El Candado del Navegador',
        subtitle: 'Comprende el protocolo HTTPS y certificados.',
        gameType: 'puzzle-vault',
        difficulty: 'Media',
        xpReward: 160,
        coinReward: 45,
        skillBonus: { skill: 'phishing', points: 14 },
        status: 'locked',
        description: 'Descubre qué significa el candado verde y cuándo un sitio aún puede ser engañoso.',
        timeEstimate: '5 min',
      },
      {
        id: 'w3-m8',
        worldId: 'world-3',
        number: 8,
        title: 'La Gran Tormenta de Phishing',
        subtitle: 'Misión Boss: Inspecciona 6 ataques en tiempo récord.',
        gameType: 'phishing-inbox',
        difficulty: 'Difícil',
        xpReward: 270,
        coinReward: 80,
        skillBonus: { skill: 'phishing', points: 24 },
        status: 'locked',
        isBoss: true,
        bossName: 'El Pescador Sombrío',
        description: 'Desafío final del Mundo 3: Neutraliza la campaña de phishing masiva y protege la escuela.',
        timeEstimate: '6 min',
      },
    ],
  },
  {
    id: 'world-4',
    number: 4,
    name: 'Ciudad Social',
    title: 'Redes Sociales',
    subtitle: 'Piensa antes de publicar y cuida tu bienestar digital.',
    motto: 'Lo que subes deja huella',
    biome: 'Metrópolis luminosa con pantallas de proyección, feeds flotantes y bulevares conectados',
    status: 'locked',
    icon: 'Share2',
    color: '#EC4899',
    accentBg: 'from-pink-50 to-rose-100/70',
    completedMissions: 0,
    totalMissions: 8,
    finalChallengeTitle: 'El Guardián Viral',
    finalChallengeDesc: 'Gestiona una cuenta escolar durante una semana simulada protegiendo la reputación y privacidad de todos.',
    missions: [
      {
        id: 'w4-m1',
        worldId: 'world-4',
        number: 1,
        title: 'El Dial de Amigos',
        subtitle: 'Configura quién puede comentar tus posts.',
        gameType: 'privacy-dial',
        difficulty: 'Fácil',
        xpReward: 130,
        coinReward: 30,
        skillBonus: { skill: 'redesSociales', points: 12 },
        status: 'locked',
        description: 'Limita los comentarios a personas que conoces en la vida real.',
        timeEstimate: '3 min',
      },
      {
        id: 'w4-m2',
        worldId: 'world-4',
        number: 2,
        title: 'La Huella Digital Eterna',
        subtitle: '¿Se borra realmente lo que eliminas?',
        gameType: 'quiz',
        difficulty: 'Fácil',
        xpReward: 135,
        coinReward: 30,
        skillBonus: { skill: 'redesSociales', points: 12 },
        status: 'locked',
        description: 'Aprende cómo las capturas de pantalla conservan fotos para siempre.',
        timeEstimate: '3 min',
      },
      {
        id: 'w4-m3',
        worldId: 'world-4',
        number: 3,
        title: 'Retos Virales Peligrosos',
        subtitle: 'Distingue bromas divertidas de riesgos físicos.',
        gameType: 'safe-risky-sort',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 35,
        skillBonus: { skill: 'redesSociales', points: 13 },
        status: 'locked',
        description: 'Aprende a no seguir modas que ponen en riesgo tu salud o la de otros.',
        timeEstimate: '4 min',
      },
      {
        id: 'w4-m4',
        worldId: 'world-4',
        number: 4,
        title: 'Foto con Amigos: El Permiso',
        subtitle: 'Preguntar antes de etiquetar.',
        gameType: 'chat-sim',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'redesSociales', points: 14 },
        status: 'locked',
        description: 'Toma la decisión respetuosa cuando un amigo no quiere aparecer en Internet.',
        timeEstimate: '4 min',
      },
      {
        id: 'w4-m5',
        worldId: 'world-4',
        number: 5,
        title: 'El Algoritmo y el Tiempo',
        subtitle: 'Controla el reloj antes de que te atrape.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'redesSociales', points: 13 },
        status: 'locked',
        description: 'Cómo funcionan las recompensas continuas y trucos para descansar la vista.',
        timeEstimate: '3 min',
      },
      {
        id: 'w4-m6',
        worldId: 'world-4',
        number: 6,
        title: 'Memoria de Ciudad Social',
        subtitle: 'Empareja normas de convivencia digital.',
        gameType: 'memory-match',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 35,
        skillBonus: { skill: 'redesSociales', points: 13 },
        status: 'locked',
        description: 'Relaciona etiquetas positivas, moderación y privacidad de historias.',
        timeEstimate: '4 min',
      },
      {
        id: 'w4-m7',
        worldId: 'world-4',
        number: 7,
        title: 'El Botón de Silenciar y Bloquear',
        subtitle: 'Tu derecho a un feed pacífico.',
        gameType: 'incident-response',
        difficulty: 'Media',
        xpReward: 160,
        coinReward: 45,
        skillBonus: { skill: 'redesSociales', points: 15 },
        status: 'locked',
        description: 'Aprende a usar las herramientas de la app para no ver contenido que te incomode.',
        timeEstimate: '4 min',
      },
      {
        id: 'w4-m8',
        worldId: 'world-4',
        number: 8,
        title: 'El Gran Reto de la Reputación',
        subtitle: 'Misión Boss: Transforma un perfil caótico en ejemplar.',
        gameType: 'puzzle-vault',
        difficulty: 'Difícil',
        xpReward: 270,
        coinReward: 80,
        skillBonus: { skill: 'redesSociales', points: 25 },
        status: 'locked',
        isBoss: true,
        bossName: 'El Eco de la Red',
        description: 'Desafío final del Mundo 4: Resuelve los 4 dilemas de Ciudad Social.',
        timeEstimate: '6 min',
      },
    ],
  },
  {
    id: 'world-5',
    number: 5,
    name: 'Zona Gamer',
    title: 'Gaming Seguro',
    subtitle: 'Juega multijugador, chatea y diviértete sin trampas.',
    motto: 'El verdadero nivel pro es jugar seguro',
    biome: 'Estadio de esports retrofuturista con plataformas de neón y hologramas de torneos',
    status: 'locked',
    icon: 'Gamepad2',
    color: '#10B981',
    accentBg: 'from-emerald-50 to-teal-100/70',
    completedMissions: 0,
    totalMissions: 8,
    finalChallengeTitle: 'La Arena del Juego Limpio',
    finalChallengeDesc: 'Supera una partida multijugador detectando fraudes de intercambio de ítems y trampas de chat de voz.',
    missions: [
      {
        id: 'w5-m1',
        worldId: 'world-5',
        number: 1,
        title: 'El Intercambio Justo',
        subtitle: 'Cuidado con los intercambios fuera del juego.',
        gameType: 'chat-sim',
        difficulty: 'Fácil',
        xpReward: 130,
        coinReward: 30,
        skillBonus: { skill: 'gamingSeguro', points: 12 },
        status: 'locked',
        description: '"Dame tu espada primero y te transfiero los puntos luego". ¿Qué haces?',
        timeEstimate: '3 min',
      },
      {
        id: 'w5-m2',
        worldId: 'world-5',
        number: 2,
        title: 'El Chat de Voz Desconocido',
        subtitle: 'Qué información no decir por el micrófono.',
        gameType: 'safe-risky-sort',
        difficulty: 'Fácil',
        xpReward: 135,
        coinReward: 30,
        skillBonus: { skill: 'gamingSeguro', points: 12 },
        status: 'locked',
        description: 'Clasifica frases: hablar de estrategias vs revelar tu edad o ciudad.',
        timeEstimate: '4 min',
      },
      {
        id: 'w5-m3',
        worldId: 'world-5',
        number: 3,
        title: 'Descargas de Mods Sospechosos',
        subtitle: 'El supuesto truco que contiene malware.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'gamingSeguro', points: 13 },
        status: 'locked',
        description: 'Por qué descargar archivos .exe prometiendo ventajas arruina tu computadora.',
        timeEstimate: '3 min',
      },
      {
        id: 'w5-m4',
        worldId: 'world-5',
        number: 4,
        title: 'Compras Integradas y Tarjetas',
        subtitle: 'Respetar el dinero y pedir autorización.',
        gameType: 'incident-response',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'gamingSeguro', points: 14 },
        status: 'locked',
        description: 'Qué hacer cuando un juego te incita a gastar en cajas de botín.',
        timeEstimate: '4 min',
      },
      {
        id: 'w5-m5',
        worldId: 'world-5',
        number: 5,
        title: 'Bloqueo a Jugadores Tóxicos',
        subtitle: 'Reporta en dos toques y sigue divirtiéndote.',
        gameType: 'chat-sim',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 35,
        skillBonus: { skill: 'gamingSeguro', points: 13 },
        status: 'locked',
        description: 'Usa los canales oficiales de reporte en lugar de responder con más enojo.',
        timeEstimate: '4 min',
      },
      {
        id: 'w5-m6',
        worldId: 'world-5',
        number: 6,
        title: 'Memoria de Gaming Seguro',
        subtitle: 'Iconos de seguridad en videojuegos.',
        gameType: 'memory-match',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'gamingSeguro', points: 13 },
        status: 'locked',
        description: 'Empareja reportes, bloqueos, moderación parental y chats seguros.',
        timeEstimate: '4 min',
      },
      {
        id: 'w5-m7',
        worldId: 'world-5',
        number: 7,
        title: 'Cuentas de Juego Compartidas',
        subtitle: 'El riesgo de perder tu progreso.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 155,
        coinReward: 45,
        skillBonus: { skill: 'gamingSeguro', points: 14 },
        status: 'locked',
        description: 'Aprende por qué cada jugador debe tener su propio usuario.',
        timeEstimate: '3 min',
      },
      {
        id: 'w5-m8',
        worldId: 'world-5',
        number: 8,
        title: 'El Torneo del Fair Play',
        subtitle: 'Misión Boss: Derrota al tramposo del servidor.',
        gameType: 'puzzle-vault',
        difficulty: 'Difícil',
        xpReward: 280,
        coinReward: 85,
        skillBonus: { skill: 'gamingSeguro', points: 25 },
        status: 'locked',
        isBoss: true,
        bossName: 'El Glitcher Oscuro',
        description: 'Desafío final del Mundo 5: Restaura el servidor con juego limpio y seguridad.',
        timeEstimate: '6 min',
      },
    ],
  },
  {
    id: 'world-6',
    number: 6,
    name: 'Bahía de Amigos',
    title: 'Amigos & Desconocidos',
    subtitle: 'Conoce los riesgos de hablar con extraños por Internet.',
    motto: 'Un avatar simpático no siempre es quien dice ser',
    biome: 'Costa con faro luminoso, puentes levadizos y murallas de confianza comunitaria',
    status: 'locked',
    icon: 'Users',
    color: '#06B6D4',
    accentBg: 'from-cyan-50 to-sky-100/70',
    completedMissions: 0,
    totalMissions: 8,
    finalChallengeTitle: 'El Perímetro de Confianza',
    finalChallengeDesc: 'Navega una situación de ingeniería social protegiendo tus límites sin aceptar citas ni regalos secretos.',
    missions: [
      {
        id: 'w6-m1',
        worldId: 'world-6',
        number: 1,
        title: 'El Perfil de Alguien que No Conoces',
        subtitle: '¿Quién está detrás de la pantalla?',
        gameType: 'chat-sim',
        difficulty: 'Fácil',
        xpReward: 135,
        coinReward: 30,
        skillBonus: { skill: 'amigosDesconocidos', points: 12 },
        status: 'locked',
        description: 'Un contacto desconocido te dice que tiene tu misma edad y va a tu colegio. Aprende a verificar.',
        timeEstimate: '4 min',
      },
      {
        id: 'w6-m2',
        worldId: 'world-6',
        number: 2,
        title: 'La Regla de Oro del Secreto',
        subtitle: 'Si te piden no contarlo a tus padres, ¡alerta!',
        gameType: 'safe-risky-sort',
        difficulty: 'Fácil',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'amigosDesconocidos', points: 13 },
        status: 'locked',
        description: 'Distingue sorpresas de cumpleaños saludables de secretos peligrosos con extraños.',
        timeEstimate: '4 min',
      },
      {
        id: 'w6-m3',
        worldId: 'world-6',
        number: 3,
        title: 'Pedir Fotos o Videos Privados',
        subtitle: 'Tu cuerpo y tu intimidad son intocables.',
        gameType: 'incident-response',
        difficulty: 'Media',
        xpReward: 155,
        coinReward: 40,
        skillBonus: { skill: 'amigosDesconocidos', points: 15 },
        status: 'locked',
        description: 'Aprende a decir "NO", cerrar la conversación y avisar de inmediato a tu adulto de confianza.',
        timeEstimate: '4 min',
      },
      {
        id: 'w6-m4',
        worldId: 'world-6',
        number: 4,
        title: 'Invitación a Encuentros en Persona',
        subtitle: 'Nunca asistas a citas de Internet.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'amigosDesconocidos', points: 14 },
        status: 'locked',
        description: 'Por qué los encuentros reales solo ocurren acompañados de tus padres.',
        timeEstimate: '3 min',
      },
      {
        id: 'w6-m5',
        worldId: 'world-6',
        number: 5,
        title: 'Los Amigos de Mis Amigos',
        subtitle: '¿Deberías aceptar solicitudes automáticas?',
        gameType: 'privacy-dial',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 35,
        skillBonus: { skill: 'amigosDesconocidos', points: 13 },
        status: 'locked',
        description: 'Configura tus filtros para que solo tus amigos directos puedan enviarte mensajes.',
        timeEstimate: '3 min',
      },
      {
        id: 'w6-m6',
        worldId: 'world-6',
        number: 6,
        title: 'Memoria del Faro',
        subtitle: 'Empareja señales de alerta y acciones seguras.',
        gameType: 'memory-match',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'amigosDesconocidos', points: 13 },
        status: 'locked',
        description: 'Relaciona banderas rojas con las respuestas correctas de protección.',
        timeEstimate: '4 min',
      },
      {
        id: 'w6-m7',
        worldId: 'world-6',
        number: 7,
        title: 'Hablar con un Adulto sin Culpa',
        subtitle: 'Si cometiste un error, no te castigarán.',
        gameType: 'chat-sim',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'amigosDesconocidos', points: 14 },
        status: 'locked',
        description: 'Practica cómo contarle a tu mamá, papá o profesor lo que ocurrió sin temor.',
        timeEstimate: '4 min',
      },
      {
        id: 'w6-m8',
        worldId: 'world-6',
        number: 8,
        title: 'El Guardián del Faro',
        subtitle: 'Misión Boss: Protege a tu grupo de amigos de un intruso.',
        gameType: 'puzzle-vault',
        difficulty: 'Difícil',
        xpReward: 280,
        coinReward: 85,
        skillBonus: { skill: 'amigosDesconocidos', points: 25 },
        status: 'locked',
        isBoss: true,
        bossName: 'La Máscara Digital',
        description: 'Desafío final del Mundo 6: Desactiva los 3 engaños del intruso.',
        timeEstimate: '6 min',
      },
    ],
  },
  {
    id: 'world-7',
    number: 7,
    name: 'Valle de Dispositivos',
    title: 'Dispositivos & Apps',
    subtitle: 'Controla lo que entra en tu tablet, teléfono y computadora.',
    motto: 'Permisos mínimos, seguridad máxima',
    biome: 'Valle tecnológico con cables de fibra subterráneos, torres de señal y antenas limpias',
    status: 'locked',
    icon: 'Smartphone',
    color: '#3B82F6',
    accentBg: 'from-blue-50 to-indigo-100/70',
    completedMissions: 0,
    totalMissions: 8,
    finalChallengeTitle: 'El Escudo de Permisos',
    finalChallengeDesc: 'Revisa e higieniza los permisos de 6 aplicaciones antes de conectarlas a la red central.',
    missions: [
      {
        id: 'w7-m1',
        worldId: 'world-7',
        number: 1,
        title: '¿Por qué la Linterna quiere mi GPS?',
        subtitle: 'Audita permisos absurdos en aplicaciones.',
        gameType: 'safe-risky-sort',
        difficulty: 'Fácil',
        xpReward: 130,
        coinReward: 30,
        skillBonus: { skill: 'dispositivos', points: 12 },
        status: 'locked',
        description: 'Clasifica permisos coherentes vs permisos sospechosos y abusivos.',
        timeEstimate: '3 min',
      },
      {
        id: 'w7-m2',
        worldId: 'world-7',
        number: 2,
        title: 'Descargar solo de Tiendas Oficiales',
        subtitle: 'El peligro de APKs y links de YouTube.',
        gameType: 'quiz',
        difficulty: 'Fácil',
        xpReward: 135,
        coinReward: 30,
        skillBonus: { skill: 'dispositivos', points: 12 },
        status: 'locked',
        description: 'Por qué App Store y Google Play revisan las apps antes de publicarlas.',
        timeEstimate: '3 min',
      },
      {
        id: 'w7-m3',
        worldId: 'world-7',
        number: 3,
        title: 'Actualizaciones del Sistema',
        subtitle: 'Por qué actualizar cierra puertas a los virus.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'dispositivos', points: 13 },
        status: 'locked',
        description: 'Descubre los parches de seguridad y por qué no ignorar el aviso del sistema.',
        timeEstimate: '3 min',
      },
      {
        id: 'w7-m4',
        worldId: 'world-7',
        number: 4,
        title: 'Wi-Fi Público sin Contraseña',
        subtitle: 'Cuidado con conectarte en la plaza o cafetería.',
        gameType: 'incident-response',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'dispositivos', points: 14 },
        status: 'locked',
        description: 'Por qué no ingresar contraseñas bancarias o personales en redes abiertas.',
        timeEstimate: '4 min',
      },
      {
        id: 'w7-m5',
        worldId: 'world-7',
        number: 5,
        title: 'Bloqueo de Pantalla Automático',
        subtitle: 'PIN, huella o rostro para proteger tu equipo.',
        gameType: 'password-forge',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 35,
        skillBonus: { skill: 'dispositivos', points: 13 },
        status: 'locked',
        description: 'Si olvidas tu tablet en el aula, ¡nadie podrá entrar a tus fotos o mensajes!',
        timeEstimate: '3 min',
      },
      {
        id: 'w7-m6',
        worldId: 'world-7',
        number: 6,
        title: 'Memoria de Dispositivos',
        subtitle: 'Conceptos de hardware y seguridad.',
        gameType: 'memory-match',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'dispositivos', points: 13 },
        status: 'locked',
        description: 'Empareja antivirus, copias de seguridad, PIN y permisos.',
        timeEstimate: '4 min',
      },
      {
        id: 'w7-m7',
        worldId: 'world-7',
        number: 7,
        title: 'Copias de Seguridad (Backup)',
        subtitle: 'No pierdas tus fotos y dibujos favoritos.',
        gameType: 'drag-drop',
        difficulty: 'Media',
        xpReward: 155,
        coinReward: 45,
        skillBonus: { skill: 'dispositivos', points: 14 },
        status: 'locked',
        description: 'Aprende a guardar tus creaciones importantes en la nube segura.',
        timeEstimate: '4 min',
      },
      {
        id: 'w7-m8',
        worldId: 'world-7',
        number: 8,
        title: 'El Cortafuegos del Valle',
        subtitle: 'Misión Boss: Desinfecta un dispositivo contaminado.',
        gameType: 'puzzle-vault',
        difficulty: 'Difícil',
        xpReward: 290,
        coinReward: 90,
        skillBonus: { skill: 'dispositivos', points: 26 },
        status: 'locked',
        isBoss: true,
        bossName: 'El Caballo de Troya',
        description: 'Desafío final del Mundo 7: Elimina 4 archivos maliciosos y restaura la tablet.',
        timeEstimate: '6 min',
      },
    ],
  },
  {
    id: 'world-8',
    number: 8,
    name: 'Cumbre del Respeto',
    title: 'Ciberacoso & Convivencia',
    subtitle: 'Convierte situaciones difíciles en decisiones seguras y empáticas.',
    motto: 'Sé un guardián, nunca un observador pasivo',
    biome: 'Montaña nevada y cristalina con santuarios de paz, puentes de amistad y torres de auxilio',
    status: 'locked',
    icon: 'HeartHandshake',
    color: '#6366F1',
    accentBg: 'from-indigo-50 to-purple-100/70',
    completedMissions: 0,
    totalMissions: 8,
    finalChallengeTitle: 'El Centinela de la Empatía',
    finalChallengeDesc: 'Intervén de forma constructiva en un grupo escolar para frenar un rumor y apoyar a un compañero.',
    missions: [
      {
        id: 'w8-m1',
        worldId: 'world-8',
        number: 1,
        title: 'El Testigo Solidario',
        subtitle: 'Qué hacer cuando se burlan de alguien en un grupo.',
        gameType: 'chat-sim',
        difficulty: 'Fácil',
        xpReward: 135,
        coinReward: 30,
        skillBonus: { skill: 'ciberacoso', points: 12 },
        status: 'locked',
        description: 'No reenviar memes dañinos, ofrecer apoyo en privado y avisar a un profesor.',
        timeEstimate: '4 min',
      },
      {
        id: 'w8-m2',
        worldId: 'world-8',
        number: 2,
        title: 'Bromas vs Agresiones',
        subtitle: '¿Cuándo una broma deja de ser graciosa?',
        gameType: 'safe-risky-sort',
        difficulty: 'Fácil',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'ciberacoso', points: 13 },
        status: 'locked',
        description: 'Si una de las personas no se ríe o se siente mal, ya no es un juego.',
        timeEstimate: '4 min',
      },
      {
        id: 'w8-m3',
        worldId: 'world-8',
        number: 3,
        title: 'Guardar Pruebas con Capturas',
        subtitle: 'Cómo documentar sin responder con insultos.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 35,
        skillBonus: { skill: 'ciberacoso', points: 13 },
        status: 'locked',
        description: 'Guarda la captura de pantalla con fecha y hora para mostrarla a las autoridades escolares.',
        timeEstimate: '3 min',
      },
      {
        id: 'w8-m4',
        worldId: 'world-8',
        number: 4,
        title: 'Cerrar Círculos Tóxicos',
        subtitle: 'Salte de grupos que te hacen daño.',
        gameType: 'incident-response',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'ciberacoso', points: 14 },
        status: 'locked',
        description: 'Tienes todo el derecho de abandonar chats donde reine la agresión.',
        timeEstimate: '4 min',
      },
      {
        id: 'w8-m5',
        worldId: 'world-8',
        number: 5,
        title: 'Empatía Digital al Teclear',
        subtitle: 'Piensa cómo leerá la otra persona tu mensaje.',
        gameType: 'chat-sim',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 35,
        skillBonus: { skill: 'ciberacoso', points: 13 },
        status: 'locked',
        description: 'El texto no transmite tono de voz: practica formular opiniones amables.',
        timeEstimate: '4 min',
      },
      {
        id: 'w8-m6',
        worldId: 'world-8',
        number: 6,
        title: 'Memoria de la Cumbre',
        subtitle: 'Valores de compañerismo en línea.',
        gameType: 'memory-match',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'ciberacoso', points: 13 },
        status: 'locked',
        description: 'Relaciona respeto, apoyo mutuo, reporte y contención.',
        timeEstimate: '4 min',
      },
      {
        id: 'w8-m7',
        worldId: 'world-8',
        number: 7,
        title: 'Líneas de Ayuda y Escucha',
        subtitle: 'A quién recurrir si te sientes abrumado.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 155,
        coinReward: 45,
        skillBonus: { skill: 'ciberacoso', points: 15 },
        status: 'locked',
        description: 'Conoce los canales gratuitos y anónimos de asistencia infantil en tu país.',
        timeEstimate: '3 min',
      },
      {
        id: 'w8-m8',
        worldId: 'world-8',
        number: 8,
        title: 'La Paz en la Cumbre',
        subtitle: 'Misión Boss: Disuelve la tormenta de rumores escolares.',
        gameType: 'puzzle-vault',
        difficulty: 'Difícil',
        xpReward: 290,
        coinReward: 90,
        skillBonus: { skill: 'ciberacoso', points: 26 },
        status: 'locked',
        isBoss: true,
        bossName: 'La Espiral del Rumor',
        description: 'Desafío final del Mundo 8: Apaga el fuego con empatía y valentía digital.',
        timeEstimate: '6 min',
      },
    ],
  },
  {
    id: 'world-9',
    number: 9,
    name: 'Laboratorio Sintético IA',
    title: 'IA & Deepfakes',
    subtitle: '¿Real o generado? Aprende a detectar contenido falso por IA.',
    motto: 'No todo lo que ves y oyes es real',
    biome: 'Complejo científico flotante con hologramas de análisis espectral y lentes biométricos',
    status: 'locked',
    icon: 'Sparkles',
    color: '#A855F7',
    accentBg: 'from-violet-50 to-purple-100/70',
    completedMissions: 0,
    totalMissions: 8,
    finalChallengeTitle: 'El Test de Realidad',
    finalChallengeDesc: 'Audita 5 piezas de contenido (2 fotos, 2 audios y 1 video) e identifica las inconsistencias sintéticas.',
    missions: [
      {
        id: 'w9-m1',
        worldId: 'world-9',
        number: 1,
        title: 'El Detector de Rostros IA',
        subtitle: 'Compara dos imágenes e identifica pistas.',
        gameType: 'ai-detector',
        difficulty: 'Fácil',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'iaDeepfakes', points: 14 },
        status: 'available',
        description: 'Busca manos con 6 dedos, pendientes asimétricos, sombras raras y fondos borrosos.',
        timeEstimate: '4 min',
      },
      {
        id: 'w9-m2',
        worldId: 'world-9',
        number: 2,
        title: 'Clonación de Voces Famosas',
        subtitle: '¿Ese youtuber realmente dijo eso?',
        gameType: 'quiz',
        difficulty: 'Fácil',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'iaDeepfakes', points: 13 },
        status: 'locked',
        description: 'Aprende cómo las herramientas de síntesis de voz imitan acentos y frases célebres.',
        timeEstimate: '3 min',
      },
      {
        id: 'w9-m3',
        worldId: 'world-9',
        number: 3,
        title: 'Imágenes Increíbles pero Falsas',
        subtitle: 'Verifica la fuente antes de asombrarte.',
        gameType: 'safe-risky-sort',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 40,
        skillBonus: { skill: 'iaDeepfakes', points: 14 },
        status: 'locked',
        description: 'Animales mitológicos, catástrofes irreales y fotos trucadas de famosos.',
        timeEstimate: '4 min',
      },
      {
        id: 'w9-m4',
        worldId: 'world-9',
        number: 4,
        title: 'Chatbots y Respuestas Alucinadas',
        subtitle: 'La IA no lo sabe todo: a veces inventa.',
        gameType: 'chat-sim',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'iaDeepfakes', points: 14 },
        status: 'locked',
        description: 'Comprueba datos históricos con libros y fuentes confiables.',
        timeEstimate: '4 min',
      },
      {
        id: 'w9-m5',
        worldId: 'world-9',
        number: 5,
        title: 'Búsqueda Inversa de Imágenes',
        subtitle: 'Descubre de dónde proviene una foto en 2 clics.',
        gameType: 'puzzle-vault',
        difficulty: 'Media',
        xpReward: 155,
        coinReward: 45,
        skillBonus: { skill: 'iaDeepfakes', points: 15 },
        status: 'locked',
        description: 'Usa herramientas de búsqueda inversa para rastrear la primera vez que se publicó una imagen.',
        timeEstimate: '5 min',
      },
      {
        id: 'w9-m6',
        worldId: 'world-9',
        number: 6,
        title: 'Memoria de la Inteligencia Artificial',
        subtitle: 'Empareja términos de tecnología y realidad.',
        gameType: 'memory-match',
        difficulty: 'Media',
        xpReward: 140,
        coinReward: 35,
        skillBonus: { skill: 'iaDeepfakes', points: 13 },
        status: 'locked',
        description: 'Relaciona prompt, deepfake, generador y verificación.',
        timeEstimate: '4 min',
      },
      {
        id: 'w9-m7',
        worldId: 'world-9',
        number: 7,
        title: 'Uso Creativo y Ético de la IA',
        subtitle: 'Aprende a usar la IA para estudiar sin copiar.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 155,
        coinReward: 45,
        skillBonus: { skill: 'iaDeepfakes', points: 15 },
        status: 'locked',
        description: 'Cómo pedir ideas para historias sin dejar que la máquina haga toda tu tarea.',
        timeEstimate: '3 min',
      },
      {
        id: 'w9-m8',
        worldId: 'world-9',
        number: 8,
        title: 'El Gran Examen de Realidad',
        subtitle: 'Misión Boss: Desenmascara al impostor generado.',
        gameType: 'ai-detector',
        difficulty: 'Difícil',
        xpReward: 300,
        coinReward: 100,
        skillBonus: { skill: 'iaDeepfakes', points: 28 },
        status: 'locked',
        isBoss: true,
        bossName: 'El Clon Sintético',
        description: 'Desafío final del Mundo 9: Descubre el video falso antes de que se propague.',
        timeEstimate: '6 min',
      },
    ],
  },
  {
    id: 'world-10',
    number: 10,
    name: 'Ciudadela de Respuesta',
    title: 'Respuesta ante Incidentes',
    subtitle: '¿Qué harías si algo sale mal? Mantén la calma y toma el control.',
    motto: 'Todo problema digital tiene solución si pides ayuda a tiempo',
    biome: 'Centro de comando de alta tecnología con pantallas de rescate, alarmas suaves y cápsulas de restauración',
    status: 'locked',
    icon: 'LifeBuoy',
    color: '#EF4444',
    accentBg: 'from-rose-50 to-red-100/70',
    completedMissions: 0,
    totalMissions: 8,
    finalChallengeTitle: 'Emergencia Ciberespacial',
    finalChallengeDesc: 'Resuelve un incidente completo: desde el clic erróneo hasta la recuperación total de la cuenta.',
    missions: [
      {
        id: 'w10-m1',
        worldId: 'world-10',
        number: 1,
        title: 'Hiciste clic por error: ¿Y ahora qué?',
        subtitle: 'Los primeros 60 segundos después de una equivocación.',
        gameType: 'incident-response',
        difficulty: 'Fácil',
        xpReward: 145,
        coinReward: 35,
        skillBonus: { skill: 'respuestaIncidentes', points: 14 },
        status: 'available',
        description: 'No te asustes, no lo ocultes: cierra la ventana, desconecta y habla con un adulto.',
        timeEstimate: '4 min',
      },
      {
        id: 'w10-m2',
        worldId: 'world-10',
        number: 2,
        title: 'Recuperar una Cuenta Bloqueada',
        subtitle: 'Pasos oficiales de soporte de la plataforma.',
        gameType: 'puzzle-vault',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'respuestaIncidentes', points: 14 },
        status: 'locked',
        description: 'Usa el correo de tus padres para restablecer la contraseña de manera segura.',
        timeEstimate: '4 min',
      },
      {
        id: 'w10-m3',
        worldId: 'world-10',
        number: 3,
        title: 'El Análisis con Antivirus',
        subtitle: 'Escanea el disco y limpia amenazas.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 155,
        coinReward: 40,
        skillBonus: { skill: 'respuestaIncidentes', points: 15 },
        status: 'locked',
        description: 'Cómo funciona la cuarentena y la eliminación de archivos sospechosos.',
        timeEstimate: '3 min',
      },
      {
        id: 'w10-m4',
        worldId: 'world-10',
        number: 4,
        title: 'Cerrar Sesión en Otros Dispositivos',
        subtitle: 'Desconecta tu cuenta a distancia.',
        gameType: 'safe-risky-sort',
        difficulty: 'Media',
        xpReward: 150,
        coinReward: 40,
        skillBonus: { skill: 'respuestaIncidentes', points: 14 },
        status: 'locked',
        description: 'Si usaste la computadora de la biblioteca, asegúrate de desvincular tu sesión.',
        timeEstimate: '4 min',
      },
      {
        id: 'w10-m5',
        worldId: 'world-10',
        number: 5,
        title: 'Avisar a tus Amigos',
        subtitle: '"Si te escriben desde mi cuenta, ¡no soy yo!"',
        gameType: 'chat-sim',
        difficulty: 'Media',
        xpReward: 155,
        coinReward: 45,
        skillBonus: { skill: 'respuestaIncidentes', points: 15 },
        status: 'locked',
        description: 'Avisa rápido para evitar que el atacante estafe a tus contactos haciéndose pasar por ti.',
        timeEstimate: '4 min',
      },
      {
        id: 'w10-m6',
        worldId: 'world-10',
        number: 6,
        title: 'Memoria del Equipo de Rescate',
        subtitle: 'Empareja los pasos de recuperación de desastres.',
        gameType: 'memory-match',
        difficulty: 'Media',
        xpReward: 145,
        coinReward: 35,
        skillBonus: { skill: 'respuestaIncidentes', points: 13 },
        status: 'locked',
        description: 'Relaciona calmarse, pedir ayuda, cambiar claves y revisar dispositivos.',
        timeEstimate: '4 min',
      },
      {
        id: 'w10-m7',
        worldId: 'world-10',
        number: 7,
        title: 'El Protocolo Familiar',
        subtitle: 'Tener una lista de contraseñas guardadas en papel seguro en casa.',
        gameType: 'quiz',
        difficulty: 'Media',
        xpReward: 160,
        coinReward: 45,
        skillBonus: { skill: 'respuestaIncidentes', points: 15 },
        status: 'locked',
        description: 'Una libreta física guardada por tus padres es inmune a los hackers de Internet.',
        timeEstimate: '3 min',
      },
      {
        id: 'w10-m8',
        worldId: 'world-10',
        number: 8,
        title: 'La Gran Emergencia Ciberespacial',
        subtitle: 'Misión Boss Final: Restablece todo el ecosistema CiberKids.',
        gameType: 'incident-response',
        difficulty: 'Difícil',
        xpReward: 350,
        coinReward: 120,
        skillBonus: { skill: 'respuestaIncidentes', points: 30 },
        status: 'locked',
        isBoss: true,
        bossName: 'El Gran Apagón Digital',
        description: 'Desafío cumbre de CiberKids: Guía a todos los mundos a través del protocolo maestro de rescate.',
        timeEstimate: '8 min',
      },
    ],
  },
];

export const PHOTO_HOTSPOTS: GameHotspot[] = [
  {
    id: 'hs-school-badge',
    label: 'Insignia escolar en uniforme',
    isSensitiveRisk: true,
    feedbackTitle: '¡Gran ojo de detective!',
    feedbackText: 'El escudo del uniforme revela el colegio al que asistes cada mañana. Es mejor ocultarlo con un emoji o sticker.',
    ciberReaction: 'excited',
    rect: { x: 38, y: 46, width: 14, height: 16 },
  },
  {
    id: 'hs-school-name',
    label: 'Cartel: "Colegio San Patricio"',
    isSensitiveRisk: true,
    feedbackTitle: '¡Excelente observación!',
    feedbackText: 'El letrero indica exactamente tu ubicación habitual. Cualquier desconocido sabría dónde encontrarte.',
    ciberReaction: 'thinking',
    rect: { x: 8, y: 14, width: 34, height: 18 },
  },
  {
    id: 'hs-house-number',
    label: 'Placa de dirección: "Nº 42"',
    isSensitiveRisk: true,
    feedbackTitle: '¡Riesgo crítico detectado!',
    feedbackText: 'La numeración de la casa y el nombre de la calle nunca deben verse en Internet para proteger tu hogar.',
    ciberReaction: 'surprised',
    rect: { x: 74, y: 22, width: 18, height: 18 },
  },
  {
    id: 'hs-pet-tag',
    label: 'Placa del perro con teléfono',
    isSensitiveRisk: true,
    feedbackTitle: '¡Qué buen reflejo!',
    feedbackText: 'La medalla de tu mascota lleva grabado el teléfono de tu familia. ¡Ese dato es confidencial!',
    ciberReaction: 'celebrating',
    rect: { x: 62, y: 68, width: 22, height: 22 },
  },
  {
    id: 'hs-backpack-name',
    label: 'Mochila con nombre "Lucas M."',
    isSensitiveRisk: true,
    feedbackTitle: '¡Buen hallazgo!',
    feedbackText: 'Tu nombre completo en la mochila facilita que extraños simulen conocerte. Mejor usar iniciales o stickers.',
    ciberReaction: 'happy',
    rect: { x: 16, y: 64, width: 20, height: 22 },
  },
  {
    id: 'hs-soccer-ball',
    label: 'Balón de fútbol',
    isSensitiveRisk: false,
    feedbackTitle: '¡Elemento seguro!',
    feedbackText: '¡Compartir tu pasión por el deporte es genial y seguro! No revela tu ubicación ni datos personales.',
    ciberReaction: 'happy',
    rect: { x: 42, y: 78, width: 16, height: 18 },
  },
];

export const BADGES_DATA: AchievementBadge[] = [
  {
    id: 'badge-first-step',
    title: 'Primer paso',
    description: 'Comenzaste tu entrenamiento como guardián del ciberespacio.',
    icon: 'Footprints',
    unlocked: true,
    unlockedAt: '12 Sep 2026',
    category: 'Iniciación',
    rarity: 'Común',
  },
  {
    id: 'badge-detective-digital',
    title: 'Detective digital',
    description: 'Descubriste todos los datos sensibles ocultos en una foto pública.',
    icon: 'Search',
    unlocked: true,
    category: 'Privacidad',
    rarity: 'Raro',
  },
  {
    id: 'badge-password-apprentice',
    title: 'Maestro de contraseñas',
    description: 'Creaste una combinación blindada con mayúsculas, números y símbolos.',
    icon: 'Key',
    unlocked: true,
    unlockedAt: '14 Sep 2026',
    category: 'Seguridad',
    rarity: 'Raro',
  },
  {
    id: 'badge-anti-scam',
    title: 'Escudo Antifraude',
    description: 'Ignoraste con éxito una falsa oferta de monedas gratis en un juego.',
    icon: 'ZapOff',
    unlocked: false,
    category: 'Phishing',
    rarity: 'Épico',
  },
  {
    id: 'badge-privacy-guardian',
    title: 'Guardián de la privacidad',
    description: 'Supera 5 desafíos seguidos protegiendo información personal.',
    icon: 'ShieldCheck',
    unlocked: false,
    category: 'Privacidad',
    rarity: 'Épico',
  },
  {
    id: 'badge-deepfake-hunter',
    title: 'Cazador de Deepfakes',
    description: 'Detectaste inconsistencias en un video manipulado con Inteligencia Artificial.',
    icon: 'Eye',
    unlocked: false,
    category: 'Inteligencia Artificial',
    rarity: 'Épico',
  },
  {
    id: 'badge-safe-gamer',
    title: 'Gamer Responsable',
    description: 'Completaste 5 misiones de multijugador seguro sin compartir datos.',
    icon: 'Gamepad2',
    unlocked: false,
    category: 'Gaming',
    rarity: 'Raro',
  },
  {
    id: 'badge-incident-hero',
    title: 'Héroe de la Ciudadela',
    description: 'Resolviste una crisis digital manteniendo la calma y avisando a un adulto.',
    icon: 'LifeBuoy',
    unlocked: false,
    category: 'Respuesta',
    rarity: 'Épico',
  },
];
